name: FixUUID
version: '${project.version}'
main: com.github.fixuuid.FixUUID
api-version: '1.13'
authors: [ 3cxc ]
description: UUID修复，以防止未进入过服务器的玩家与服务器UUID的不一致
website: https://github.com/3cxc/FixUUID
depend: [ProtocolLib]
commands:
  whitelist:
    description: 白名单指令

permissions:
  fixuuid.whitelist.admin:
    description: 本插件的管理员权限
    default: op
    children:
      fixuuid.whitelist.add: true
      fixuuid.whitelist.remove: true
      fixuuid.whitelist.list: true
      fixuuid.whitelist.reload: true
  fixuuid.whitelist.add:
    description: 向白名单里添加玩家
    default: op
  fixuuid.whitelist.remove:
    description: 从白名单里删除一个玩家
    default: op
  fixuuid.whitelist.reload:
    description: 重载白名单
    default: op
  fixuuid.whitelist.list:
    description: 查看在白名单内的所有玩家
    default: op